### ISSUE TITLE
Graph and horizons

### ISSUE THREAD

**Issue by Quickuser** [AdaemmerP/lpirfs#10]
Hello Dr. Adämmer,

First of all, thanks for your package, it's been really useful.

I have three questions regarding the graphs and results (I'm using lp_lin_iv() if it helps):

I've noticed that all the graphs start with horizon=1, I assume this is the first impact of the shock on the endogenous variable. But I wonder because the equation in page 4 (in your PDF) starts from h=0, which I assume that's the first response but when I observe the graph it starts from h=1. May you explain me this?

Second question is about the color, how can I get different colors for a graph if it is possible? Or at least get a different color line for the mean.

Third question, is it possible to round the values obtained from the tables?

Thank you.

**Comment by AdaemmerP** [comment]
Thank you for your questions!

I have followed the convention by Jordà (2005), namely that the first horizon,
denoted on the x-axis, equals h = 0. It is also outlined in the paper.

I have deliberately excluded any options regarding the plot functions, because the options would be too many. However, you could copy the whole code of the plot function, rename it, and adapt it to your preferences. The input would be the same. For example, the color of the line for the mean values can be changed in line 79 of the *plot_lin* function (https://github.com/AdaemmerP/lpirfs/blob/master/R/plot_lin.R). Note that the lines from 25 to 61 are used for the output of *lp_lin* and the lines from 63 to 96 for the output of *lp_lin_iv* and *lp_lin_panel*.

You could also save the impulse responses from the output and create your own figures. The vignette of the package (https://cran.r-project.org/web/packages/lpirfs/vignettes/lpirfs_vignette.html) contains the code for the figures of the appendix of the paper, which have been created "from scratch".

**Comment by Quickuser** [comment]
Thanks!
