### ISSUE TITLE
Why are the confidence interval bands at horizon 1 equal to the results_lin_iv$irf_lin_mean values? 

### ISSUE THREAD

**Issue by sarah1399** [AdaemmerP/lpirfs#26]
Shouldn’t every parameter estimate at each horizon have an associated standard error? At the first horizon the standard errors seem to be 0 for all examples generated, and hence the confidence intervals are not wide at the first point. Thanks!

**Comment by AdaemmerP** [comment]
The package follows the convention by Jorda, namely that the first horizon in the output and plots equals h = 0
(https://journal.r-project.org/archive/2019/RJ-2019-052/RJ-2019-052.pdf, page 426).

The example in the package for lp_lin_iv() uses Gov as the shock variable as well as an endogenous variable. The beta coefficient at h = 0 is 1 with no uncertainty since you regress the variable on itself. The coefficients and standard errors start to vary with h = 1.
