### ISSUE TITLE
Hypothesis testing and coefficient interpretation 

### ISSUE THREAD

**Issue by assilaflip** [AdaemmerP/lpirfs#28]
Thank you for a convenient package. Two points: 
1) How do we go about running t-tests on whether the two shocks (negative and positive) are statistically significantly different (i.e. coefficients on s1 shock and s2 shock are statistically significantly different at each horizon). We are testing for sign asymmetry in monetary policy shocks. We have tried using built-in packages in R for hypothesis testing, but because the results are stored unlike those for a typical regression (eg. we have no access to the variance-covariance matrix), we are not sure how to run the t-tests. Do you have sample code that could be used? 
2) Are the results on the negative shocks (s1) flipped already? i.e. should we interpret the results as a one unit decrease (from say -1 to -2) has the s1 coefficient effect on the dependent variable, or are the results not flipped so the interpretation would follow those for a typical OLS (i.e. a one unit increase, from -2 to -1) has the s1 coefficient effect (in which case we have to flip the sign ourselves). Thanks!

**Comment by AdaemmerP** [comment]
1. This has not been implemented. What about comparing the confidence intervals for both shocks at each horizon directly?
2. The interpretation of the results depend on the creation of your switching variable. The package does not do any "flipping" by itself. Which function are you using? In case of "lp_nl_iv" you can interpret the  results as a one unit increase/decrease, because the impulse responses correspond to the estimated coefficients of an OLS model. Be aware, however, when you do transformations on your shock variable.
