### ISSUE TITLE
cumul_mult question

### ISSUE THREAD

**Issue by AndroAsatashvili** [AdaemmerP/lpirfs#38]
Hello, thanks for the package and the resources, its been very helpful for my undergraduate thesis. I have some questions regarding the cumul_mult option.

Given that I'm trying to modify lp_nl so I can get cumulative respones (similar to lp_nl_iv) I noticed that the IRF change very little (if nothing at all). Is this supposed to happen? 

Thank you

**Comment by AdaemmerP** [comment]
This is not surprising given that you are subtracting a fixed value, `y_(t-1)`, from the response variable `y`. This will result in a vertical shift in y, but it should not affect the slope coefficients, which are the impulse responses within the local projection framework. It will however affect the intercept, but this is not relevant here. I only implemented this approach because I saw it being used in the literature.
